In [26]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
%matplotlib inline
import numpy as np
import statsmodels.api as sm
import math
import heapq as hq

In [27]:
lc=pd.read_csv("lc2final.csv")

In [28]:
lc.head()

,B,C,D,E,F,G,funded_amnt,annual_inc,issue_year,dti,fico_avg,emp_length,revol_bal,term_num,default
0,0,0,0,0,0,0,14500,58761.0,2015,21.94,697.0,0,15449,36,0
1,1,0,0,0,0,0,1000,65000.0,2017,25.68,727.0,1,5154,36,0
2,0,0,0,1,0,0,16800,65000.0,2013,5.93,672.0,10,17843,60,0
3,0,0,0,1,0,0,18000,101000.0,2016,28.91,692.0,2,24126,60,1
4,0,1,0,0,0,0,26000,65000.0,2015,24.92,662.0,8,40580,36,0

In [29]:
lc.columns

Index(['B', 'C', 'D', 'E', 'F', 'G', 'funded_amnt', 'annual_inc', 'issue_year',
       'dti', 'fico_avg', 'emp_length', 'revol_bal', 'term_num', 'default'],
      dtype='object')

In [35]:
x=lc[['B', 'C', 'D', 'E', 'F', 'G', 'dti', 'fico_avg', 'emp_length', 'revol_bal', 'term_num']]
y=lc['default']
x=sm.tools.tools.add_constant(x)
logit=sm.Logit(y,x)

result=logit.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.458919
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                default   No. Observations:                24977
Model:                          Logit   Df Residuals:                    24965
Method:                           MLE   Df Model:                           11
Date:                Sun, 26 Jan 2020   Pseudo R-squ.:                 0.07855
Time:                        22:03:36   Log-Likelihood:                -11462.
converged:                       True   LL-Null:                       -12440.
                                        LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9609      0.507      1.896      0.058      -0.033       1.954
B              0.5388      0.076      7.134      0.000       0.391       0.687
C              0.9499      0.076     12.446      0.000       0.800       1.099
D              1.2781      0.081     15.718      0.000       1.119       1.437
E              1.4949      0.090     16.547      0.000       1.318       1.672
F              1.6092      0.113     14.278      0.000       1.388       1.830
G              1.8561      0.173     10.757      0.000       1.518       2.194
dti            0.0253      0.002     12.731      0.000       0.021       0.029
fico_avg      -0.0063      0.001     -8.908      0.000      -0.008      -0.005
emp_length    -0.0222      0.004     -5.090      0.000      -0.031      -0.014
revol_bal  -3.808e-06   9.76e-07     -3.903      0.000   -5.72e-06    -1.9e-06
term_num       0.0200      0.002     12.009      0.000       0.017       0.023
==============================================================================
"""

In [49]:
from sklearn.neighbors import KNeighborsClassifier
x=lc[['B', 'C', 'D', 'E', 'F', 'G', 'dti', 'fico_avg', 'emp_length', 'revol_bal', 'term_num']]
y=lc['default']
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [50]:
neigh.predict(x.loc[0:100])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [51]:
neigh.predict_proba(x.loc[0:10])

array([[1. , 0. ],
       [0.6, 0.4],
       [0.8, 0.2],
       [0.6, 0.4],
       [0.8, 0.2],
       [0.8, 0.2],
       [0.8, 0.2],
       [1. , 0. ],
       [0.8, 0.2],
       [1. , 0. ],
       [1. , 0. ]])

In [36]:
x=lc[['B', 'C', 'D', 'E', 'F', 'G', 'dti', 'fico_avg', 'emp_length', 'revol_bal', 'term_num']]
y=lc['default']
logit=sm.Logit(y,x)

result=logit.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.458991
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                default   No. Observations:                24977
Model:                          Logit   Df Residuals:                    24966
Method:                           MLE   Df Model:                           10
Date:                Sun, 26 Jan 2020   Pseudo R-squ.:                 0.07840
Time:                        22:03:56   Log-Likelihood:                -11464.
converged:                       True   LL-Null:                       -12440.
                                        LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
B              0.5887      0.071      8.270      0.000       0.449       0.728
C              1.0126      0.069     14.628      0.000       0.877       1.148
D              1.3474      0.073     18.429      0.000       1.204       1.491
E              1.5677      0.082     19.075      0.000       1.407       1.729
F              1.6851      0.106     15.950      0.000       1.478       1.892
G              1.9316      0.168     11.497      0.000       1.602       2.261
dti            0.0254      0.002     12.824      0.000       0.022       0.029
fico_avg      -0.0050      0.000    -37.722      0.000      -0.005      -0.005
emp_length    -0.0220      0.004     -5.029      0.000      -0.031      -0.013
revol_bal  -3.836e-06   9.73e-07     -3.941      0.000   -5.74e-06   -1.93e-06
term_num       0.0197      0.002     11.895      0.000       0.016       0.023
==============================================================================
"""

In [19]:
B1=lc["B"]*0.5887
C1=lc["C"]*1.0126
D1=lc["D"]*1.3474
E1=lc["E"]*1.5677
F1=lc["F"]*1.6851
G1=lc["G"]*1.9316
dti2=lc["dti"]*0.0254
fico_avg2=lc["fico_avg"]*(-0.0050)
emp_length2=lc["emp_length"]*(-0.0220)
revol_bal2=lc["revol_bal"]*(-3.836e-06)
term_num2=lc["term_num"]*0.0197
default2=lc["default"]
llc=pd.concat([B1,C1,D1,E1,F1,G1,dti2,fico_avg2,emp_length2,revol_bal2,term_num2,default2],axis=1)
llc.head()

,B,C,D,E,F,G,dti,fico_avg,emp_length,revol_bal,term_num,default
0,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.557276,-3.485,-0.000,-0.059262,0.7092,0
1,0.5887,0.0000,0.0,0.0000,0.0,0.0,0.652272,-3.635,-0.022,-0.019771,0.7092,0
2,0.0000,0.0000,0.0,1.5677,0.0,0.0,0.150622,-3.360,-0.220,-0.068446,1.1820,0
3,0.0000,0.0000,0.0,1.5677,0.0,0.0,0.734314,-3.460,-0.044,-0.092547,1.1820,1
4,0.0000,1.0126,0.0,0.0000,0.0,0.0,0.632968,-3.310,-0.176,-0.155665,0.7092,0

In [22]:
llc.to_csv("llc0126.csv")
llc=pd.read_csv("llc0126.csv")
llc.head()

,Unnamed: 0,id,B,C,D,E,F,G,dti,fico_avg,emp_length,revol_bal,term_num,default,sum_logic
0,0,0,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.557276,-3.485,0.000,-0.059262,0.7092,0,-2.277786
1,1,1,0.5887,0.0000,0.0,0.0000,0.0,0.0,0.652272,-3.635,-0.022,-0.019771,0.7092,0,-1.726599
2,2,2,0.0000,0.0000,0.0,1.5677,0.0,0.0,0.150622,-3.360,-0.220,-0.068446,1.1820,0,-0.748124
3,3,3,0.0000,0.0000,0.0,1.5677,0.0,0.0,0.734314,-3.460,-0.044,-0.092547,1.1820,1,-0.112533
4,4,4,0.0000,1.0126,0.0,0.0000,0.0,0.0,0.632968,-3.310,-0.176,-0.155665,0.7092,0,-1.286897